# Generated by Django 6.0.1 on 2026-02-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
