# Generated by Django 6.0.1 on 2026-03-04 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee_password', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_address', models.TextField(blank=True, null=True)),
                ('employee_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('employee_langauges', models.JSONField(blank=True, max_length=255, null=True)),
                ('employee_skills', models.JSONField(blank=True, max_length=255, null=True)),
                ('employee_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('store_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'cx_employee',
            },
        ),
    ]
